name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2023-09-20
version: '9.5.11'
project: 'drupal'
datestamp: 1695228127
