name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2023-09-20
version: '9.5.11'
project: 'drupal'
datestamp: 1695228127
